#!/usr/bin/env python3
import os
import json
import time
import cv2
import torch
import numpy as np

import rclpy
from rclpy.node import Node
from rclpy.action import ActionServer
from rclpy.executors import MultiThreadedExecutor
from rclpy.qos import QoSProfile, QoSDurabilityPolicy, QoSReliabilityPolicy

from sensor_msgs.msg import Image
from std_msgs.msg import Float32MultiArray, Int32MultiArray
from cv_bridge import CvBridge

from ultralytics import YOLO
from ultralytics.nn.modules import head, block

# Try to import action classes generated by rosidl for ROS2
try:
    from bt_qualify.action import Align, Config
except Exception:
    Align = None
    Config = None


class YoloDetector(Node):
    def __init__(self):
        super().__init__('yolo_detector')
        self.get_logger().info('Nó de detecção YOLO iniciado')

        self.bridge = CvBridge()

        # Model setup
        script_dir = os.path.dirname(os.path.abspath(__file__))
        model_path = os.path.join(script_dir, "ffc_rs_26_det_only.pt")
        # compatibility fixes mirroring your ROS1 code
        head.Segment26 = head.Segment
        block.Proto26 = block.Proto

        # load model
        self.model = YOLO(model_path)
        # send to GPU if available
        try:
            self.model.to("cuda")
        except Exception as e:
            self.get_logger().warn(f"Falha ao mover modelo para cuda: {e}")

        self.get_logger().info(f"PyTorch enxerga a GPU? {torch.cuda.is_available()}")
        try:
            dev_name = torch.cuda.get_device_name(0) if torch.cuda.is_available() else 'Nenhuma'
        except Exception:
            dev_name = 'Nenhuma'
        self.get_logger().info(f"O YOLO está rodando no dispositivo: {self.model.device}")
        self.get_logger().info(f"Nome da GPU: {dev_name}")

        # runtime state
        self.target_classes = [0]

        # QoS for image transport: keep depth 1, best-effort may be desired for camera streams
        qos_img = QoSProfile(depth=1)
        qos_img.reliability = QoSReliabilityPolicy.BEST_EFFORT

        # Publishers / Subscribers
        self.det_image_pub = self.create_publisher(Image, '/ultralytics/detection/image', qos_img)
        self.features_pub = self.create_publisher(Float32MultiArray, '/auv/image/features/detected', 10)

        # subscribe to camera image
        self.image_sub = self.create_subscription(Image, '/oak/rgb/image_raw', self.process_image, qos_img)

        # subscribe to class filter topic
        self.classes_sub = self.create_subscription(Int32MultiArray, '/YOLO/Classe', self.update_classes_cb, 10)

        # action servers (placeholders if actions unavailable)
        if Align is not None:
            self._align_action_server = ActionServer(
                self,
                Align,
                'align_action_server',
                execute_callback=self._execute_align_action
            )
            self.get_logger().info('Align action server started')
        else:
            self.get_logger().warn('Align action type not available; align action server not started')

        if Config is not None:
            self._config_action_server = ActionServer(
                self,
                'config_server',
                execute_callback=self._execute_config_action
            )
            self.get_logger().info('Config action server started')
        else:
            self.get_logger().warn('Config action type not available; config action server not started')

        # load json references if present
        self.json_data = {}
        self.load_json_refs()

    # -------------- Action callbacks (minimal placeholders) ----------------
    def _execute_align_action(self, goal_handle):
        # A simple placeholder: you should adapt this to your real align logic
        self.get_logger().info('Align action received (placeholder) — succeeding immediately')
        result = Align.Result() if Align is not None else None
        if result is not None:
            # set a 'success' attribute if exists
            if hasattr(result, 'success'):
                setattr(result, 'success', True)
        goal_handle.succeed()
        return result

    def _execute_config_action(self, goal_handle):
        self.get_logger().info('Config action received (placeholder) — succeeding immediately')
        result = Config.Result() if Config is not None else None
        goal_handle.succeed()
        return result

    # -------------- Helpers / callbacks ----------------------------------
    def load_json_refs(self):
        script_dir = os.path.dirname(__file__)
        caminho_json = os.path.join(script_dir, 'objetos_config.json')
        try:
            with open(caminho_json, 'r') as f:
                self.json_data = json.load(f)
            self.get_logger().info(f'Carregado {caminho_json}')
        except Exception as e:
            self.get_logger().warn(f'Não foi possível carregar {caminho_json}: {e}')
            self.json_data = {}

    def process_image(self, msg: Image):
        try:
            frame = self.bridge.imgmsg_to_cv2(msg, "bgr8")
            self.inferencia(frame)
        except Exception as err:
            self.get_logger().error(f"Erro ao converter imagem: {err}")

    def update_classes_cb(self, msg: Int32MultiArray):
        try:
            self.target_classes = list(msg.data)
            self.get_logger().info(f"Filtro de classes atualizado para: {self.target_classes}")
        except Exception as e:
            self.get_logger().error(f"Erro em update_classes_cb: {e}")

    def inferencia(self, imagem):
        # Run model inference (force GPU device if available)
        try:
            results = self.model(
                imagem,
                conf=0.30,
                verbose=False,
                classes=self.target_classes,
                device="cuda:0" if torch.cuda.is_available() else self.model.device,
            )
        except Exception as e:
            self.get_logger().error(f"Erro na inferência do modelo: {e}")
            return

        # Collect boxes into Float32MultiArray
        msg_pixels = Float32MultiArray()
        pixels_array = []

        for result in results:
            for box in getattr(result, 'boxes', []):
                try:
                    coords = box.xyxy[0].cpu().numpy().tolist()
                    pixels_array.extend(
                        [
                            float(coords[0]), 
                            float(coords[1]), 
                            float(coords[2]), 
                            float(coords[3])
                        ]
                    )
                except Exception as e:
                    self.get_logger().warn(f'Erro ao extrair coords da caixa: {e}')

        if len(pixels_array) > 0:
            msg_pixels.data = pixels_array
            self.features_pub.publish(msg_pixels)

        # Publish annotated image if someone is subscribed
        try:
            sub_count = self.det_image_pub.get_subscription_count()
        except Exception:
            sub_count = 0

        if sub_count > 0:
            try:
                annotated_frame = results[0].plot()
                if annotated_frame is None:
                    return

                # ensure uint8
                if annotated_frame.dtype != np.uint8:
                    annotated_frame = annotated_frame.astype(np.uint8)

                # use CvBridge to convert
                msg_out = self.bridge.cv2_to_imgmsg(annotated_frame, encoding='bgr8')
                msg_out.header.stamp = self.get_clock().now().to_msg()
                msg_out.header.frame_id = "stereo_camera"
                self.det_image_pub.publish(msg_out)
            except Exception as e:
                self.get_logger().error(f"Erro ao publicar imagem anotada: {e}")


def main(args=None):
    rclpy.init(args=args)
    node = YoloDetector()
    executor = MultiThreadedExecutor()
    executor.add_node(node)
    try:
        executor.spin()
    except KeyboardInterrupt:
        pass
    finally:
        executor.shutdown()
        node.destroy_node()
        rclpy.shutdown()


if __name__ == "__main__":
    main()